"""empty message

Revision ID: 33930d9429d0
Revises: 9903451f25d2
Create Date: 2025-12-07 11:31:09.619080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33930d9429d0'
down_revision = '9903451f25d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###
