"""Adicionando campos de endereco e personalizacao

Revision ID: 7739f2bb2e6d
Revises: 371ce3e17d20
Create Date: 2025-11-27 08:25:56.123936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7739f2bb2e6d'
down_revision = '371ce3e17d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('neighborhood', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('complement', sa.String(length=100), nullable=True))
        batch_op.drop_column('address')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customizations_json', sa.Text(), nullable=True))
        batch_op.drop_column('observations')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('neighborhood', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('complement', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('complement')
        batch_op.drop_column('neighborhood')
        batch_op.drop_column('number')
        batch_op.drop_column('street')
        batch_op.drop_column('whatsapp')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observations', sa.VARCHAR(length=250), nullable=True))
        batch_op.drop_column('customizations_json')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('complement')
        batch_op.drop_column('neighborhood')
        batch_op.drop_column('street')
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
