"""tabela horarios

Revision ID: b65af3d69214
Revises: f5aa6571cd30
Create Date: 2025-12-06 16:01:32.337884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65af3d69214'
down_revision = 'f5aa6571cd30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.String(length=5), nullable=True),
    sa.Column('close_time', sa.String(length=5), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_of_week')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_schedule')
    # ### end Alembic commands ###
